### ISSUE TITLE
Can you add OwnTracks to this AiO?

### ISSUE THREAD

**Issue by JonTheNiceGuy** [jbags81/fabric-home-assistant#15]
http://owntracks.org/booklet/guide/broker/

**Comment by fabaff** [comment]
[mosquitto](http://mosquitto.org/) is already included (with [websockets support](https://github.com/home-assistant/fabric-home-assistant/blob/master/fabfile.py#L187)). Beside that is Home Assistant shipping en [embedded broker](https://home-assistant.io/components/mqtt/#use-the-embedded-broker).

**Comment by JonTheNiceGuy** [comment]
Hey @fabaff thanks for that! I think I was hoping that the steps where it creates the CA and Server Certs would be part of the script. I'll see what I can turn up by prodding and poking at it for now. I might even manage to turn this into a PR if I can make something good happen! :smile:
