### ISSUE TITLE
hass_rpi_installer.sh fails with syntax error

### ISSUE THREAD

**Issue by dustyjewett** [jbags81/fabric-home-assistant#16]
When running hass_rpi_installer.sh on raspbian, I get the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 666, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 167, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/pi/fabric-home-assistant/fabfile.py", line 177
    fabric.contrib.files.append("/home/hass/.homeassistant/configuration.yaml", hacfg, use_sudo=True)
```

Raspberry Pi B, rev 000f

**Comment by dustyjewett** [comment]
Reverting to previous commit allows the script to run past this point. 
(Though, the script is still running, so we'll see how that goes)

**Comment by davedan** [comment]
Same here.

I see a commit from  jbags81 about 8 hours ago. 
@dustyjewett, by going one version before are you going to be able to resolve 0.25 dependencies?

**Comment by davedan** [comment]
I can't write in the proyect but it's very easy to fix.

File fabfile.py. Line 175  & Line 268 there's a missing ')' in those commands:

Line 175 reads:  
sudo("/srv/hass/hass_venv/bin/hass --script ensure_config --config /home/hass/.homeassistant"

and should be:
sudo("/srv/hass/hass_venv/bin/hass --script ensure_config --config /home/hass/.homeassistant")

Line 268 reads:
sudo("/srv/hass/hass_venv/bin/hass --script ensure_config --config /home/hass/.homeassistant"

and should be:
sudo("/srv/hass/hass_venv/bin/hass --script ensure_config --config /home/hass/.homeassistant")

once modified in my local copy everything worked as expected.

hope this helps.

**Comment by patchedsoul** [comment]
Fixed, thanks for the good catch.
