### ISSUE TITLE
No rule to make taret

### ISSUE THREAD

**Issue by mwoods329** [jbags81/fabric-home-assistant#17]
Installation terminated with this:

[localhost] put: Makefile -> /srv/hass/src/open-zwave-control-panel/Makefile
[localhost] sudo: make
[localhost] out: make: **\* No rule to make target '/srv/hass/src/python-openzwave/openzwave/cpp/src/Options.h', needed by 'ozwcp.o'. Stop.
[localhost] out:

Warning: sudo() received nonzero return code 2 while executing 'make'!

Subsequent attempts had the same failure.
RPi 2
Latest installation of Jessie (fresh install this AM)

**Comment by relicscoth** [comment]
Same here. Reboots after this failure. Tried run an update to see if it would recover or resume missing components, but the virtual env is not created at this point.

Rasp 2 model B, v1.1, running the auto-installer from https://home-assistant.io/getting-started/installation-raspberry-pi-all-in-one/

**Comment by relicscoth** [comment]
@mwoods329  did you run apt-get update before starting install? A clean image, plus updates, worked for me. My problem probably arose from something on my existing image since I didn't start fresh.

**Comment by patchedsoul** [comment]
Validated installer runs without issue. Tested on pi3 and Latest "Jessie" Raspbian build
