### ISSUE TITLE
Missing dependency libmicrohttpd-dev

### ISSUE THREAD

**Issue by fabaff** [jbags81/fabric-home-assistant#19]
:point_up: [12. August 2016 15:22](https://gitter.im/home-assistant/home-assistant/devs?at=57adcd7946610f173955282e)

Could be that libmicrohttpd-dev is an additional dependency.

**Comment by patchedsoul** [comment]
validated installer works without prompting for libmicrohttpd-dev. Was run against pi3 and latest build of jessie raspbian.
