### ISSUE TITLE
script not accepting password

### ISSUE THREAD

**Issue by snizzleorg** [jbags81/fabric-home-assistant#2]
```
.
.
.
Your Raspberry Pi will reboot when the installer is complete.
Install is starting...
[localhost] sudo: apt-get update
[localhost] Login password for 'pi': 
[localhost] Login password for 'pi': 
```

what exactly does the script do with the password? I have the ssh disabled for the user pi and I'm strictly using certificates. Is the script trying to login or just using sudo? (I gave the user pi sudo rights)

**Comment by patchedsoul** [comment]
At this point both.

Sent from my iPhone
Please excuse my brevity or any typo's

On May 17, 2016, at 8:07 AM, snizzleorg <notifications@github.com<mailto:notifications@github.com>> wrote:

.
.
.
Your Raspberry Pi will reboot when the installer is complete.
Install is starting...
[localhost] sudo: apt-get update
[localhost] Login password for 'pi':
[localhost] Login password for 'pi':

what exactly does the script do with the password? I have the ssh disabled for the user pi and I'm strictly using certificates. Is the script trying to login or just using sudo? (I gave the user pi sudo rights)

##

**Comment by snizzleorg** [comment]
both what? ssh? So I need ssh enabled for pi?

**Comment by patchedsoul** [comment]
Correct

Sent from my iPhone
Please excuse my brevity or any typo's

On May 17, 2016, at 2:04 PM, snizzleorg <notifications@github.com<mailto:notifications@github.com>> wrote:

both what? ssh? So I need ssh enabled for pi?

##

**Comment by patchedsoul** [comment]
user pi having SSH access to and from the rPI is a current requirement.
