### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [jbags81/fabric-home-assistant#22]
Include a check for fabric at the begining.  I am using a lite version of Jessie, and its the only thing I have to install before the installer works. Other than that GJ!

**Comment by Landrash** [comment]
There's a check for fabric in the beginning at https://github.com/home-assistant/fabric-home-assistant/blob/master/hass_rpi_installer.sh#L38 .
Can this be related to #24 ?

**Comment by patchedsoul** [comment]
closing - no issue
