### ISSUE TITLE
Question : Is there a preinstalled image ?

### ISSUE THREAD

**Issue by madhan5000** [jbags81/fabric-home-assistant#23]
I am having a hard time installing it on my raspberry pi. I wonder if you have pre installed image it would be easier to get started. Please let me know. Keep up the good work !!

**Comment by Landrash** [comment]
There's currently no preinstalled image.
It's been discussed and somewhat in the works. No ETA currently.

**Comment by brianjking** [comment]
@Landrash Perhaps once PiBakery gets support for different ISOs HomeAssistant could get baked in with this tool https://github.com/davidferguson/pibakery/

**Comment by patchedsoul** [comment]
See [Getting Started](https://home-assistant.io/getting-started/installation-raspberry-pi-image/) doc's for image info
