### ISSUE TITLE
Hardcoded pip location

### ISSUE THREAD

**Issue by gpeavy** [jbags81/fabric-home-assistant#24]
hass_rpi_installer.sh assumes pip is installed at /usr/bin/pip. My installations has it located at /usr/local/bin/pip.

**Comment by Landrash** [comment]
@gpeavy What installation/enviroment are you currently on?

**Comment by gpeavy** [comment]
NOOBS 1.9.2 / RASPBIAN JESSIE

**Comment by patchedsoul** [comment]
NOOBS isn't a supported distro

**Comment by gpeavy** [comment]
What do you mean NOOBS isn't a supported distro.  It installs RASPBIAN JESSIE. And the recommend intallation method for Raspberry Pi.

**Comment by Landrash** [comment]
The script wasn't developed with NOOBS in mind.

**Comment by gpeavy** [comment]
Either way.  Why are you hard coding the path to pip?  It can easily be installed in different locations and should already be on the PATH.

**Comment by Landrash** [comment]
Your welcome to submit a pull request.
