### ISSUE TITLE
pycrypto fails

### ISSUE THREAD

**Issue by aarya123** [jbags81/fabric-home-assistant#25]
Pycrypto fails to install when using pip. The fix for this was to actually install via apt-get. Can we fix this?

**Comment by Landrash** [comment]
@aarya123 This needs more information.
- What distribution?
- What platform?
- Python version?

**Comment by aarya123** [comment]
This is on the a clean version of Jessie lite. The script took care of installing everything, including python

**Comment by fabaff** [comment]
https://community.home-assistant.io/t/one-timer-installer-fails-on-raspberry-pi-3/7470

**Comment by patchedsoul** [comment]
fixed and tested in current script
