### ISSUE TITLE
Error on raspberry install

### ISSUE THREAD

**Issue by navigonic** [jbags81/fabric-home-assistant#29]
Trying with or without sudo doesn't change, the installer gives the error: 
hass_rpi_installer.sh: line 81: fab: command not found

What can one do?

**Comment by Landrash** [comment]
Line 81 in the fab file is the following ` sudo("apt-get upgrade -y")`.
If that fails there's most likely something underlying that gone wrong.
Are you doing this on a vanilla raspbian image?
