### ISSUE TITLE
Can't log into desktop GUI

### ISSUE THREAD

**Issue by Dracoy** [jbags81/fabric-home-assistant#3]
Starting from a fresh install of Raspbian, I was able to log into the desktop GUI fine. I next did the AIO install and everything went fine except when I try to log into the desktop GUI, it fails to login.

Same screen as this guy: https://mobile.twitter.com/Dapgicc/status/351746633186308096

I am using the right login/password because if I use the wrong one it kicks a wrong password message.

When I log-in, the screen goes black for a second and kicks me back to login page. I searched online and tried a ton of different methods and still can't login to the desktop GUI.

SSH and terminal functions work fine. I posted on Reddit and another user has the same issue.

**Comment by arsaboo** [comment]
@jbags81 mentioned in the Gitter chatroom that to remedy, SSH into your pi, and run: `sudo rm /etc/profile.d/motd.sh`

I hope that the issue will be fixed in the next update.

**Comment by Dracoy** [comment]
That worked thanks! Someone also posted it on Reddit too. Fantastic!

**Comment by patchedsoul** [comment]
I've purged the MOTD function from the script. No issues should be seen like this going forward.

**Comment by jbags81** [comment]
closing - fix implemented.
