### ISSUE TITLE
libwebsockets tar.gz can't be downloaded

### ISSUE THREAD

**Issue by fabaff** [jbags81/fabric-home-assistant#32]
Original report: https://github.com/home-assistant/home-assistant/issues/4739

After installing the lastest "RASPBIAN JESSIE LITE" version, update and upgrade on my Pi 3, I run the All-in-one installer. Everything except mqtt works as expected. Trying to configure Mosquitto, I found an issue with libwebsockets in the install log. This issue later prevents Mosquitto from working. I then try and goto the link [libwebsockets-1.4-chrome43-firefox-36.tar.gz](https://libwebsockets.org/git/libwebsockets/snapshot/libwebsockets-1.4-chrome43-firefox-36.tar.gz) and found the zip is no longer there which would explain the error `gzip: stdin: not in gzip format`. I know later versions of libwebsockets are not compatiable with Mosquitto. Is this a bug or did I do something wrong? 

**Home Assistant release (`hass --version`):**
0.34.2

**Python release (`python3 --version`):**
Python 3.4.2

**OS version**
RASPBIAN JESSIE LITE
Version:November 2016
Release date:2016-11-25
Kernel version:4.4
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"

**Hardware**
*these are the specs for all 4 processors
processor       : 3*
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

**Log file**
```
[localhost] sudo: curl -O https://libwebsockets.org/git/libwebsockets/snapshot/libwebsockets-1.4-chrome43-firefox-36.tar.gz
[localhost] out:
[localhost] out: SSH is enabled and the default password for the 'pi' user has not been changed.
[localhost] out: This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.
[localhost] out:
[localhost] out:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[localhost] out:                                  Dload  Upload   Total   Spent    Left  Speed
[localhost] out:
[localhost] out:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[localhost] out:   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[localhost] out: 100  2469    0  2469    0     0   1169      0 --:--:--  0:00:02 --:--:--  1170
[localhost] out: 100  2469    0  2469    0     0   1168      0 --:--:--  0:00:02 --:--:--  1169
[localhost] out:

[localhost] sudo: tar xvf libwebsockets*
[localhost] out:
[localhost] out: SSH is enabled and the default password for the 'pi' user has not been changed.
[localhost] out: This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.
[localhost] out:
[localhost] out:
[localhost] out: gzip: stdin: not in gzip format
[localhost] out: tar: Child returned status 1
[localhost] out: tar: Error is not recoverable: exiting now
[localhost] out:
```
...

```
[localhost] out: mosquitto.c:47:29: fatal error: libwebsockets.h: No such file or directory
[localhost] out:  #  include <libwebsockets.h>
[localhost] out:                              ^
[localhost] out: compilation terminated.
[localhost] out: Makefile:15: recipe for target 'mosquitto.o' failed
[localhost] out: make[1]: *** [mosquitto.o] Error 1
[localhost] out: make[1]: Leaving directory '/srv/hass/src/mosquitto-1.4.9/src'
[localhost] out: Makefile:21: recipe for target 'mosquitto' failed
[localhost] out: make: *** [mosquitto] Error 2
[localhost] out:
```

**Comment by patchedsoul** [comment]
previous Mosquitto refactor addressed this. package is installed from repo preventing need for libwebsockets DL.
