### ISSUE TITLE
ImportError: No module named 'packaging'

### ISSUE THREAD

**Issue by bgiwi** [jbags81/fabric-home-assistant#40]
Fresh image of Rasbian Jessie Lite on Pi3 model B, only changes to default system are expansion of filesystem, turned on ssh and change of timezone.

Ran using: wget -Nnv https://raw.githubusercontent.com/home-assistant/fabric-home-assistant/master/hass_rpi_installer.sh && chown pi:pi hass_rpi_installer.sh && bash hass_rpi_installer.sh -n

pip.log debug attached. (Renamed to .txt so Git would allow upload)
[pip.log.txt](https://github.com/home-assistant/fabric-home-assistant/files/728531/pip.log.txt)

**Comment by matt-cahill** [comment]
Seeing the same thing, as discussed here: https://community.home-assistant.io/t/install-failing-with-the-aio-installer/10359

python3-pip works before the script is run if installed via apt but fails with the missing module error for all installs afterwards.

Have worked around it successfully by installing the python.org version of pip3, symlinking it from /usr/local/bin to /usr/bin and running the hass script again.

**Comment by hemalchevli** [comment]
I too was having the same issue,  I followed the instruction in the link you provided(followed this instruction by mrtips https://community.home-assistant.io/t/install-failing-with-the-aio-installer/10359/6) and its installing now.
Thanks

**Comment by fabaff** [comment]
@jbags81 can you please take a look?

**Comment by fabaff** [comment]
Perhaps this helps: https://community.home-assistant.io/t/one-timer-installer-fails-on-raspberry-pi-3/7470/42

**Comment by patchedsoul** [comment]
Sorry, work was busy. I'll have a look today and get it sorted.

**Comment by patchedsoul** [comment]
root issue was due to aged pip and dependencies not being built due to this. resolved in latest fixes.

**Comment by fabaff** [comment]
Thanks
