### ISSUE TITLE
hass_rpi_installer.sh: line 129: fab: command not found

### ISSUE THREAD

**Issue by sascha-hemi** [jbags81/fabric-home-assistant#41]
Hello,
i know how to solve the problem but not why this error appears.

sudo -i
apt-get purge -y python3-pip
wget https://bootstrap.pypa.io/get-pip.py
python3 ./get-pip.py
apt-get install python3-pip

**Comment by matt-cahill** [comment]
I think this is the same as issue #40

**Comment by patchedsoul** [comment]
root issue was due to aged pip. resolved in latest fixes.
