### ISSUE TITLE
User change from hass to homeassistant has broken existing upgrade path

### ISSUE THREAD

**Issue by duckpuppy** [jbags81/fabric-home-assistant#45]
While trying to upgrade my homeassistant install using `fab upgrade_homeassistant`, I get an error

```
localhost] Login password for 'pi':
[localhost] out: sudo: unknown user: homeassistant
[localhost] out: sudo: unable to initialize policy plugin
[localhost] out:


Warning: sudo() received nonzero return code 1 while executing 'source /srv/homeassistant/homeassistant_venv/bin/activate && pip3 install homeassistant --upgrade'!


Done.
```

My HA install was done using the user `hass`, not `homeassistant`.  It looks like that change happened in commit 72b8a26 along with many other changes relating to changing the name of the user and several directories from `hass` to `homeassistant`.

Is there documentation on all changes that need to be made to update an existing install?  I can rename the user and rename the home directory for that user if that's all that's necessary, but I really want to be sure.

**Comment by patchedsoul** [comment]
Upgrading via the previously embedded fabric function has been removed. Please follow the projects standard instructions for updating Home Assistant.
