### ISSUE TITLE
Unable to start OZWCP on RPi AiO

### ISSUE THREAD

**Issue by fabaff** [jbags81/fabric-home-assistant#46]
**Home Assistant release (`hass --version`):**
0.38.2

**Python release (`python3 --version`):**
Python 3.4.3

**Description of problem:**
Unable to start OZWCP.
```bash
$ cd /srv/homeassistant/src/open-zwave-control-panel/
$ sudo ./ozwcp -p 8888
sudo: ./ozwcp: command not found
```

**Steps to reproduce:**
Clean install latest raspian Jessie lite
Clean install Home Assistant .38.2 AiO

**Comment by patchedsoul** [comment]
I'll have a look. Could anyone dealing with this post a hastebin of the installation_output text. This will help troubleshoot.

**Comment by patchedsoul** [comment]
Was due to libopenzwave moving to 0.3.3 from 0.3.2. Successfully ran and tested AiO against Raspbian Jessie-Lite (04/10/2017) image.

**Comment by benji87** [comment]
@patchedsoul can still replicate this issue on a clean install of Raspian Jessie Lite 4.4 and Home Assistant 0.44.1 using the AiO install. Any solution for this?
