### ISSUE TITLE
AIO installation aborts 

### ISSUE THREAD

**Issue by poughkeepsee** [jbags81/fabric-home-assistant#47]
I had to reinstall HA and used the AIO installer. I had used it previously without any issues. 
Right now, it just fails every single time. I have Raspbian 1.2 running on a Raspberry Pi 3.

I basically flashed the Raspbian image, entered PuTTY, updated & upgraded and ran the AIO curl. It goes without any issues for about 40min in the installation, and then it gets to a point where the RPi just restarts and looses connection to PuTTY (also tried installing w/ screen & keyboard connected, same result).

Last thing I get on the installation log is:
Warning: sudo() received nonzero return code 1 while executing 'ln -s /usr/local/lib/python3.4/dist-packages/cec /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages'!

Here you can access the entire instalation log:
https://drive.google.com/file/d/0B8x-gIVzQ7IKeXAzbWpOeXh4WlU/view

I would love if someone could help me out. I've tried this about 7 times (formatting SD, flashing Raspbian, update & upgrade, trying to install AIO). I really running out of options and ideas, and the good guys over @HA Gitter couldn't help me also.

PS: The log file shows some dependencies as already installed because it had failed previously and this was  my second try. Despite this, my last and subsequent tries - even when doing a fresh install and running AIO for the first time - all had the exact same result and same error.

**Comment by ramdisk00** [comment]
I can't install HA using the AIO, its broken. I have the same problem

**Comment by patchedsoul** [comment]
successfully ran and tested AiO against Raspbian Jessie-Lite (04/10/2017) image.

**Comment by dbroome1978** [comment]
I get the same error - do you need a new ticket opened?  A google search showed several people with this problem
