### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by FlyersPh9** [jbags81/fabric-home-assistant#5]
After entering:
`wget -Nnv https://raw.githubusercontent.com/home-assistant/fabric-home-assistant/master/hass_rpi_installer.sh && bash hass_rpi_installer.sh -n;`

I get the error message:
`/usr/bin/wget: /usr/bin/wget: cannot execute binary file`

I have installed a fresh copy of Raspian Jessie using [NOOBS 1.9.1](https://www.raspberrypi.org/downloads/noobs/) on a Raspberry Pi B+.

**Comment by patchedsoul** [comment]
Why did you add bash??

**Comment by FlyersPh9** [comment]
Sorry, that was a typo.  I've edited my original post to remove that.  I did however figure out that the install works if I install Jessie without NOOBS.

**Comment by patchedsoul** [comment]
Correct. NOOBS isn't supported.
