### ISSUE TITLE
AIO installer broken

### ISSUE THREAD

**Issue by ramdisk00** [jbags81/fabric-home-assistant#51]
New PI 3 with 7" display 16gb sd card, after running the AIO installer I get this message.

`Warning: sudo() received nonzero return code 1 while executing 'ln -s /usr/local/lib/python3.4/dist-packages/cec /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages'!`

**Comment by ramdisk00** [comment]
AIO install has been broken now for some time, many many reports on it's failure to install with so many different errors and just stop installing. As of today there is no update to the AIO installer right? or is there, please point me to how to get the AIO to work

**Comment by patchedsoul** [comment]
Open a pull request with the fixes in place.  lol

I'll have a look as soon as possible.

**Comment by patchedsoul** [comment]
successfully ran and tested AiO against Raspbian Jessie-Lite (04/10/2017) image.
