### ISSUE TITLE
Mosquitto starts but needs to be restarted

### ISSUE THREAD

**Issue by Lennyz1988** [jbags81/fabric-home-assistant#53]
Running latest Jessie.

After I boot my pi up, Mosquitto needs to be restarted before clients will be able to detect the server.

If I type "mosquitto" in the terminal then I get the message that Mosquitto is working. Clients however are unable to find the servers.

> pi@raspberrypi:~ $ mosquitto
> 1495362619: mosquitto version 1.4.11 (build date Mon, 20 Feb 2017 22:47:27 +0000) starting
> 1495362619: Using default config.
> 1495362619: Opening ipv4 listen socket on port 1883.
> 1495362619: Error: Address already in use
> 

I need to restart Mosquitto before clients will be able to find the server. 

These commands work however clients will be unable to find the server:

> sudo /etc/init.d/mosquitto stop
> sudo /etc/init.d/mosquitto start

This works for getting the clients to connect:

> 
> sudo /etc/init.d/mosquitto stop
> mosquitto -d

**Comment by Lennyz1988** [comment]
It's related to the passwd file used by Mosquitto. You first need to remove it and then recreate it.

> sudo rm /etc/mosquitto/pwfile
> sudo mosquitto_passwd /etc/mosquitto/pwfile [username]

**Comment by patchedsoul** [comment]
Update to support "Stretch" is coming in a couple days, and will address this.
