### ISSUE TITLE
Optimize: Change fabfile.py to clone at depth=1

### ISSUE THREAD

**Issue by steverhoades** [jbags81/fabric-home-assistant#54]
I noticed that the script currently grabs the complete commit history for each git repo.  The script would execute much faster if it simply checked out a depth of 1.

For instance:
```
git clone https://github.com/OpenZWave/python-openzwave.git
```
to
```
git clone --depth 1 https://github.com/OpenZWave/python-openzwave.git -b python3
```

Perhaps this is only an issue for me at the moment as I arduously attempt to get this installed on my pi Model B over wifi.

**Comment by patchedsoul** [comment]
Update to support "Stretch" is coming in a couple days, and will address this.
