### ISSUE TITLE
Python version issue

### ISSUE THREAD

**Issue by ChrisCHEN05** [jbags81/fabric-home-assistant#60]
Python3 on Raspbian has been updated from version 3.4 to 3.5. However, several symbolic link commands have not been updated from 'python3.4' to 'python3.5', which will result as some warnings.

```
[localhost] sudo: ldconfig
[localhost] sudo: ln -s /usr/local/lib/python3.4/dist-packages/cec /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages
[localhost] out: ln: failed to create symbolic link '/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages': No such file or directory
[localhost] out: 

Warning: sudo() received nonzero return code 1 while executing 'ln -s /usr/local/lib/python3.4/dist-packages/cec /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages'!

```

**Comment by mpigsley** [comment]
Looks like the openzwave control panel symbolic links to the config need to be updated as well.

```
if pi_hardware == "armv7l":
    sudo("ln -sd /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.3-py3.4-linux-armv7l.egg/config")
else:
    sudo("ln -sd /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.3-py3.4-linux-armv**6**l.egg/config")
```

**Comment by patchedsoul** [comment]
Update to support "Stretch" is coming in a couple days, and will address this.

**Comment by curtisolson** [comment]
Any ETA on this? Still getting the Python version error. Any way to manually complete the install? I changed the failing sym link command, but no idea where in the install this happens. I'm guessing there is a lot of commands that weren't ran after the sym link failure.

**Comment by curtisolson** [comment]
As a work around, you can use an earlier raspbian image. This is the latest image that has python3 3.4. I haven't fully tested, but openwave and mosquitto seems to have installed correctly.
https://downloads.raspberrypi.org/raspbian/images/raspbian-2017-07-05/

**Comment by firstof9** [comment]
It's line 267 of fabfile.py that throws the error, you can manually execute: ```ln -s /usr/local/lib/python3.5/dist-packages/cec /srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages``` and reboot.

**Comment by quammy** [comment]
> ...and reboot

Will it then continue the installation by itself?

**Comment by firstof9** [comment]
At that step the install has completed already.

**Comment by quammy** [comment]
Thank you firstof9. Is it possible to access the fabfile.py file before running the installation? Where can I find it?

**Comment by firstof9** [comment]
in the ```fabric-home-assistant``` directory

**Comment by quammy** [comment]
thank you @firstof9. I ran the line 
`sudo ln -s /usr/local/lib/python3.5/dist-packages/cec /srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages`
and it returned immediately, no delay at all. Is it correct?

**Comment by firstof9** [comment]
Correct it produces no output when it completes successfully.

**Comment by ghost** [comment]
Any update when this will be included in the main stream?

I'm looking to rebuild my pi HA all in one setup and ideally want to use the latest python version 3.6 and latest raspbian image so happy to help test etc.
