### ISSUE TITLE
Open Z-Wave config symlink

### ISSUE THREAD

**Issue by balloob** [jbags81/fabric-home-assistant#8]
See home-assistant/home-assistant.io#514

Different Raspberry Pi builds have different install dir because path contains architecture:

`…/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config`

**Comment by Landrash** [comment]
Another symlink that could be added would be for the zwcfg file.
Currently OZWCP and HA will have separate configurations files but these could be symlinked so that changes such as name etc done in OZWCP will be reflected in HA.

**Comment by patchedsoul** [comment]
Looking at it now.

**Comment by patchedsoul** [comment]
This could possibly be added in a future update, but isn't being considered now. I welcome a PR if you'd like to see it sooner.
