### ISSUE TITLE
Cython not required as of 0.3.0+ of python-openzwave

### ISSUE THREAD

**Issue by salt-lick** [jbags81/fabric-home-assistant#9]
Per OpenZWave's changelog, Cython is no longer needed to install python-openzwave ( as of 0.3.0 ).

[OpenZWave's Changelog](https://github.com/OpenZWave/python-openzwave/blob/master/CHANGELOG.txt#L78)

Do think think this would speed up the overall install a bit?

**Comment by patchedsoul** [comment]
I think it will help a lot. Thanks for the info. I'll see about removing this.

Sent from my iPhone
Please excuse my brevity or any typo's

On Jun 15, 2016, at 3:00 PM, Steven Barnes <notifications@github.com<mailto:notifications@github.com>> wrote:

Per OpenZWave's changelog, Cython is no longer needed to install python-openzwave ( as of 0.3.0 ).

OpenZWave's Changeloghttps://github.com/OpenZWave/python-openzwave/blob/master/CHANGELOG.txt#L78

Do think think this would speed up the overall install a bit?

##

**Comment by salt-lick** [comment]
Was I wrong? Is Cython still required?
